### ISSUE TITLE
Fix code editor style/mode 

### ISSUE THREAD

**Issue by kunstmusik** [csound/web-ide#10]
Editor is not currently setting csound editor mode nor setting monokai theme correctly. Code looks correct in src/pages/Editor/Editor.tsx and shortcut is being set correctly.

**Comment by hlolli** [comment]
Commit f64ef7a3d44d52a7cf7cc87a2bd96447345f574e fixes the syntax highligting.

Some regression in the Editor that needs to be fixed.

The solution is to use "codemirror" instead of "react-codemirror" for adding plugins. Plus I changed to react-codemirror2, which is a newer and more recently maintained react wrapper.
