### ISSUE TITLE
Fix profile list updates for project create/delete

### ISSUE THREAD

**Issue by eddyc** [csound/web-ide#46]

**Comment by hlolli** [comment]
I'm having a look now at the firestore subscription for the projectEditor, since I just want to decouple the initialization from the subscription, I'll mostly be refactoring functions, I wont be touching the profile subscription for now, other than comment out the parts that are affected from my changes.

**Comment by hlolli** [comment]
I ended up not decoupling it, rather initialize the whole project without the files, and seperately create subscription on the files. But what I think is important is that for every subscription, I make sure that I unsubscribe when I don't use it anymore

https://github.com/csound/web-ide/blob/e601ed8f7fb79e3a7b219d904145293dcf6637a0/src/components/ProjectEditor/ProjectEditor.tsx#L76-L84

and update will only touch the document that was changes, leaving everything else untouched, same goes for remove and add.

On master there's probably due to misunderstanding a rather aggressive update change https://github.com/csound/web-ide/blob/master/src/components/Projects/actions.tsx#L71 but I hope the current develop will have this under control, to ensure update, I use a new lastModified timestamp react key for the editor, meaning that an update must trigger rerender (the changes could be so slight that a component wont update otherwise).

**Comment by hlolli** [comment]
Now this is handled by subscribers properly, so this can be closed
