### ISSUE TITLE
will not render crossFM example from manual - FLTK opcodes?

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#57]
the crossFM opcode example from the manual does not render - could it be because of the FLTK opcodes in the example?

**Comment by hlolli** [comment]
You are correct, fltk doesn't work with the Web-IDE and will never work. Because fltk is based on desktop libraries, which also happen to be deprecated afaik.

The correct solution to this problem is this: https://github.com/csound/manual/pull/193

Using sliders with the WebIDE will be introduced very soon, but that would most likely be WebIDE specific code, but we are still discussing the best way forward.
