### ISSUE TITLE
Request:  Support Real-time MIDI input

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#67]

**Comment by hlolli** [comment]
This should already work even if it's not configurable, it's just that this only works in google-chrome at the moment(I don't have midi device to test, since I'm constantly at my gf's place these days). But midi routing and configuration is definitely high on our priority of things to implement before proper release.

**Comment by csounder** [comment]
I do use google chrome.  It says in the console that MIDI is not supported (or so begging like this). I can send the exact message later tonight or tomorrow if that would help.

Maybe since you were spending time away from your studio, this might be a good reason to implement the virtual midi keyboard into the Csound Web-IDE E :-)

I am happy to report that running MIDI instruments from a standard MIDI file using the -F command line option does work correctly. And that's pretty great!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by kunstmusik** [comment]
Yes MIDI is definitely one I want. But as Hlodver mentioned, it is only implemented in Chrome browsers.  For iOS, Chrome is implemented with a Webview that's essentially the same as Safari and that does not support WebMIDI.  Firefox has had an open issue in their tracker for WebMIDI for years and I'm not sure about the status.  Since this is all about requiring support in by the browser vendor, our hands will be tied, but we'll get it going for whatever platform supports it.

**Comment by csounder** [comment]
For some reason, my Chrone browser did not recognize my MIDI controller.  I will try again

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by kunstmusik** [comment]
Ah if you're testing with the Web-IDE, I'm not sure it's configured to turn
on.  (I think Hlodver was talking about it being supported underneath the
hood.) Exposing a dropdown to choose midi device and things like that
shouldn't take too long and we'll have to control it from the host side
rather than Csound and it's -M system.  I think rather than waste time on
it now for you, let us get back to you when we have it test and know it's
in.

**Comment by csounder** [comment]
OK. I can wait.  Classes begin in 2 weeks and I am happy to report that I have more students registered for Csound this summer than in any previous semester 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by kunstmusik** [comment]
Yeah no worries, probably will be a couple days if not tomorrow. :).
